name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      working-directory: ./tests
      run: make
    - name: run test
      working-directory: ./tests
      run: |
            OUTPUT=$(./build/tests_runner)
            echo "$OUTPUT"
