name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      working-directory: ./tests
      run: make
    - name: run tests
      working-directory: ./tests
      run: |
        ./build/tests_runner
        if [ $? -eq 1 ]; then
          echo "Tests returned exit code 1 but were successful."
          exit 1
        fi
